use_frameworks!
use_modular_headers!

target 'Override_Example' do
  platform :ios, '11.0'

  pod 'YMOverride', :path => '../'

  target 'Override_Tests' do
    pod 'YMOverrideTestSupport', :path => '../'

    pod 'Quick', '~>1.3'
    pod 'Nimble', '~>7.1'
    pod 'Nimble-Snapshots', '~>6.7'
    pod 'SwiftLint', '~>0.26'
  end
end

target 'Override_Example-TV' do
  platform :tvos, '11.0'

  pod 'YMOverride', :path => '../'
end
