use_frameworks!
use_modular_headers!

target 'Override_Example' do
  platform :ios, '11.0'

  pod 'YMOverride', :path => '../'

  target 'Override_Tests' do
    pod 'YMOverrideTestSupport', :path => '../'

    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
    pod 'SwiftLint'
  end
end

target 'Override_Example-TV' do
  platform :tvos, '11.0'

  pod 'YMOverride', :path => '../'
end
